[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.CHECK]
description = "check code"
script = ['''
cargo fmt --check --all
cargo check
cargo clippy --all --all-features --tests -- -D warnings
''']

[tasks.TEST]
description = "run tests"
script = ['''
cargo test --all-features
''']

[tasks.FIX_CODE]
description = "fix code"
script = ['''
cargo fmt
cargo clippy --all --all-features --tests --fix
cargo fix
''']

[tasks.BUILD_IMAGE]
workspace = false
command = "docker"
args = ["build", "-t", "rdb-app", "."]