name: build-image

on:
  push:
    tags:
      - 'v*'

jobs:
  build_image:
    name: build_image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/app:${{ github.ref_name }}
