name: ci

on:
  push:
    branches: [ main ]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.81.0

      - run: makers CHECK

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.81.0

      - name: cargo test
        run: cargo test --all-features

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings