name: Coverage

on:
  push:
    branches: [ main, update ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.81.0
      - run: rustup show
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - uses: romeovs/lcov-reporter-action@v0.3.1
        with:
         lcov-file: ./lcov.info